kind: pipeline
name: default

steps:
- name: plugin upload
  image: plugins/docker
  settings:
    repo: tphoney/test
    username: tphoney
    password:
      from_secret: docker_password
    tags: latest
    dockerfile: Dockerfile
