kind: pipeline
name: default

steps:
  - name: hello
    image: golang
    commands:
      - uname -a
      - go version
  - name: ping
    image: redis
    commands:
      - sleep 60
      - redis-cli -h red ping
  - name: last step
    image: golang
    commands:
      - ls -al
services:
  - name: red
    image: redis
