kind: pipeline
type: vm
name: testing

pool:
  use: testpool

steps:
- name: bare metal
  commands:
    - env
    - touch  /tmp/aws/drone/src/metal
- name: container create
  image: alpine
  commands:
    - touch  /tmp/aws/drone/src/container
    - ls -al /tmp/aws/drone/src/
- name: check volumes work
  commands:
    - ls -al /tmp/aws/drone/src/
- name: docker
  image: plugins/docker
  settings:
    dockerfile: Dockerfile
    repo: tphoney/test
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    auto_tag: true
    auto_tag_suffix: linux-amd64
- name: manifest
  image: plugins/manifest:1.2
  settings:
    auto_tag: 'true'
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    spec: manifest.yaml
    ignore_missing: true
trigger:
  ref:
  - refs/tags/**
