kind: pipeline
type: kubernetes
name: default

steps:
  - name: hello
    image: golang
    commands:
      - uname -a
      - go version
  - name: failer
    image: alpine
    commands:
      - exit 2
  - name: ping
    image: redis
    commands:
      - timeout 40 sleep 5
      - redis-cli -h red ping
      
services:
  - name: red
    image: redis
