kind: pipeline
name: default

steps:
- name: display go version
  image: golang
  pull: if-not-exists
  commands:
  - go version
- name: jira
  image: plugins/jira
  settings:
    connect_key:
      from_secret: connect_key
    connect_hostname: https://8e34-82-26-10-225.eu.ngrok.io
    instance: droneio
    project: TEST
    instance: d1wilko
    environment_name: staging
    log_level: debug
    pipeline: bash_plugin
