---
kind: pipeline
name: pipeline-1

steps:
  - name: step-1
    image: alpine
    commands:
      - sleep 10
      - echo "Hello from pipeline-1"

trigger:
  ref:
    - refs/heads/main
    - refs/tags/**
    - refs/pull/**

---
kind: pipeline
name: pipeline dependant on pipeline-1

platform:
  os: linux
  arch: amd64

steps:
  - name: step-1
    image: alpine
    commands:
      - echo "pipeline dependant on pipeline-1"

trigger:
  ref:
    - refs/heads/main
    - refs/tags/**
    - refs/pull/**

depends_on:
  - pipeline-1


---
kind: pipeline
name: pipeline parallel

platform:
  os: linux
  arch: amd64

steps:
  - name: step-1
    image: alpine
    commands:
      - echo "pipeline parallel"

trigger:
  ref:
    - refs/heads/main
    - refs/tags/**
    - refs/pull/**

depends_on:
  - pipeline-1
