kind: pipeline
name: default

steps:
- name: display go version
  image: golang
  pull: if-not-exists
  commands:
  - go version
- name: oom
  image: progrium/stress
  pull: if-not-exists
  commands:
  # - tail /dev/zero
    - stress -m 500 --vm-keep 
- name: display go version part2
  image: golang
  pull: if-not-exists
  commands:
  - go version
