kind: pipeline
name: default

steps:
- name: run plugins/drone-diagnostics plugin
  image: plugins/drone-diagnostics
  pull: if-not-exists
  commands:
    - env
    - ping www.github.com -w 5
    - traceroute -T -p 443 www.github.com
    - dig www.apple.com
    - echo "end of test"
    - this should fail
