kind: pipeline
type: vm
name: colour

pool:
  use: testpool

steps:
- name: colour
  image: alpine
  commands:
  -  ls -al --color=auto
- name: color
  image: hongwenjun/lolcat
  commands:
  -  lolcat /app/docker_cmd.txt
