kind: pipeline
type: docker
name: beech/docker/ubi8/python36

steps:
  - name: debug
    image: python:3.6
    commands:
      - ls -al /var/log/
      - /bin/cat /var/log/messages
      - /bin/false
