kind: pipeline
type: docker
name: beech/docker/ubi8/python36

steps:
  - name: debug
    image: ubi8/python36
    commands:
      - /bin/cat /var/log/dnf.log | /bin/wc -l
      - /bin/cat /var/log/dnf.log
      - /bin/false
