---
kind: pipeline
type: docker
name: registry.access.redhat.com/ubi7/ubi

clone:
  disable: true
steps:
  - name: drone test
    image: registry.access.redhat.com/ubi7/ubi
    commands:
      - /usr/bin/tail -3000 /var/log/anaconda/journal.log
      - /usr/bin/echo "Output complete."
      - /bin/false   
