kind: pipeline
name: default

steps:
- name: failure ignore
  image: golang
  pull: if-not-exists
  failure: ignore
  commands:
  - asadsd
- name: env
  image: golang
  pull: if-not-exists
  failure: ignore
  commands:
  - env
---
kind: pipeline
name: default2

steps:
- name: failure
  image: golang
  pull: if-not-exists
  commands:
  - asadsd
- name: env
  image: golang
  pull: if-not-exists
  failure: ignore
  commands:
  - env
  when:
    status:
      failure
      success
