kind: pipeline
type: aws
name: default

pool:
  use: ubuntu

steps:
  - name: check install
    commands:
      - cat /var/log/cloud-init-output.log
      - hostname -f
      - ifconfig
      - touch /tmp/blaaaa
 - name: plugin
   image: plugins/docker
   settings:
     dry_run: true
     repo: foo/bar
     tags: latest
   volumes:
     - name: cache
       path: /go
  - name: imagey + commands
    image: golang
    commands:
      - go version
      - go help
      - ls -al /tmp
  - name: docker status
    commands:
      - docker ps -a
  - name: ping
    image: redis
    commands:
      - redis-cli -h red ping
  - name: check host volume
    commands:
      - ls /tmp
      
services:
  - name: red
    image: redis

volumes:
- name: cache
  temp: {}
