kind: pipeline
type: vm
name: default

pool:
  use: ubuntu 
steps:
  # - name: print env
  #   image: alpine:latest
  #   commands:
  #     - ls -al
  #     - sleep 2
  #     - echo ${DRONE_COMMIT_SHA:0:7}.${DRONE_BUILD_NUMBER}
  - name: docker
    image: plugins/docker:latest
    pull: never
    environment:
      SSH_KEY: LS0tLS1CRUdJTiBPUEVOU1NIIFBSSVZBVEUgS0VZLS0tLS0KYjNCbGJuTnphQzFyWlhrdGRqRUFBQUFBQkc1dmJtVUFBQUFFYm05dVpRQUFBQUFBQUFBQkFBQUJGd0FBQUFkemMyZ3RjbgpOaEFBQUFBd0VBQVFBQUFRRUE0dVZJRTVJUjZmemY4Q1R5N3dVU2UrY25ZTUxHRWJrTEtENWRTYjRqc0ExODlmOE9YSUpzCmYzZHNqWkl4eVoyUHlTU3lLUkNtaHluYk8rajZaSjBPMnVaWWI2VU9EQW5VZGdtMlduUkZIL2xUYkJNN0RMSVh5bG5HYXUKVzVpZm1aVzllem1Sc09XN1JHU2hDSVprNmZZUHRWT1lhTE5WN3ArREZjZkRRcmxETWdMK1hkbWthS3NadTNTZXBYa1VQMwpuMHdPUkdlMExzTm9pcnpCQmcveWdDVTQ0SDBEdjhzUm1OVUZIWEVleWZwOTFRYjQ3UWdCOVVlbERlQXJwQ1BXVHZqMHBUCnJBQlJqU0hpVXpQcXVDZVU4VVpoTnJidjV0VVN4Q1RZclJERERLdDZwWWp1V0tMZUM0czFCbnVDWVdCWSsvaS9pMXFTS3cKaElpckFpdGNsd0FBQThCTTBTK0VUTkV2aEFBQUFBZHpjMmd0Y25OaEFBQUJBUURpNVVnVGtoSHAvTi93SlBMdkJSSjc1eQpkZ3dzWVJ1UXNvUGwxSnZpT3dEWHoxL3c1Y2dteC9kMnlOa2pISm5ZL0pKTElwRUthSEtkczc2UHBrblE3YTVsaHZwUTRNCkNkUjJDYlphZEVVZitWTnNFenNNc2hmS1djWnE1Ym1KK1psYjE3T1pHdzVidEVaS0VJaG1UcDlnKzFVNWhvczFYdW40TVYKeDhOQ3VVTXlBdjVkMmFSb3F4bTdkSjZsZVJRL2VmVEE1RVo3UXV3MmlLdk1FR0QvS0FKVGpnZlFPL3l4R1kxUVVkY1I3SgorbjNWQnZqdENBSDFSNlVONEN1a0k5Wk8rUFNsT3NBRkdOSWVKVE0rcTRKNVR4Um1FMnR1L20xUkxFSk5pdEVNTU1xM3FsCmlPNVlvdDRMaXpVR2U0SmhZRmo3K0wrTFdwSXJDRWlLc0NLMXlYQUFBQUF3RUFBUUFBQVFBRWVSaXVxaGFJVWwvbjBCS3AKKzZPZHBiVDFCMkg0UDNtazFYWHBXa0pCMmtJNFowclZNQTBMaGtNeGwwdzcrVXM0WCt6VE9tek9CVms1R1NLMmtSSVY1cQp5ZnB0VmNEMldNM2l3bUpGeW9nTFhRVDZDK1kxUnN2TkJZa3liUlBZWjBkUkFwV0lzejY1M25IK1JRZ0FSTVdTZ1k5am9RClYwcXRoZXVZMXo1MHNYUFVSTHdZWDJqS252SmJHVHlNVUlya1prS3RwZG5wUnd6ZUZ5L0dUREpnQnVJQmJtbUtWVGdLNFcKR0daOTJScFFxeUo2N081T3RSVW5lQ3hHSEd2TVE5dDJyRnRnRjVrclBXQVl4UXI5K00yQU84YUZZTFBERW40VUlrcnM0TgpSS3Q3eVZveElzd3Z3YUtFM01rZlJDUnY4V1RFNDBkdWpmSmh0dVMyVzJMaEFBQUFnUUNIQ2FqRytTV2hHbThHUzJ6MC9DCkg2U2xGZVZYQm9LYTVkWUhtSTNCWUpMVGJkRytKaFlHUm1OZ1UyeVozayt0dGVMV0ZOdjFmSXVreFRoRVBVRXpidk8xSzcKWm9yMHJ1bkRudzJ4ZUlTa0dzOHBUYlRCblRyc3hXZHZuTHVyeFIrTjBYT2tGc0tsUUw5NFYzK081OHlWSW9PVmN3dWRiMApleUxvYndEeGM1dlFBQUFJRUE4bVM0VytlaTc0SkVtTXBGSlh5VGgwbzBKblZGVFdlUisranRsWGo3NlV3ampKUURLVWpKCkFxblZSdzJzbFFxL2pQbE1DREtZQVBNdnYwOGk1ZDdFUEpXdWRGMldjNHpUY1lPakZDczdGZnc1RXpnVWRra3lNVzh4dkQKdHkxYmxjYTFKSGpadUkvT2RHTXRBYmJIU0R4d0Nxb0tEUGFKOWNpZmFaenlXS1NVc0FBQUNCQU8raDJqYjZFWXJ1WnNicApJMGpDQzczUlRHWFlpbERDUDBQOEpzYVp3OXBsc0cyZm5PNGhxQWI4KzdNQ0JMM0I0aHNHRHNNS2lvTldpM0tUOWpyWmVmClVyZlNEeXJzTndUMmJOd0VaQzlMeGxaU1dONGZCNktPTVp4ZEF3QmdEYlo2UkNXT1BSNEtZaHlOVnhOdmRLaEQveGdyTjQKT3F5VGFIRWZnMkdPOEJabEFBQUFDblJ3UURZNU5GUlJOek09Ci0tLS0tRU5EIE9QRU5TU0ggUFJJVkFURSBLRVktLS0tLQo=
    settings:
      dockerfile: Dockerfile
      ssh_agent: default
      tags:
        - silly
      repo: tphoney/bash
      dry_run: true
