kind: pipeline
type: docker
name: promote

steps:
- name: test
  image: node
  commands:
  -  npm version

trigger:
  event:
  - promote
  target:
  - production

---

kind: pipeline
type: docker
name: build

steps:
- name: test
  image: node
  commands:
  -  npm version

