kind: pipeline
name: default

steps:
- name: display go version
  image: golang
  pull: if-not-exists
  failure: ignore
  commands:
  - asadsd
- name: display go version
  image: golang
  pull: if-not-exists
  failure: ignore
  commands:
  - env
---
kind: pipeline
name: default2

steps:
- name: display go version
  image: golang
  pull: if-not-exists
  commands:
  - asadsd
- name: display go version
  image: golang
  pull: if-not-exists
  failure: ignore
  commands:
  - env
  when:
    status:
      failure
