kind: pipeline
name: default

steps:
- name: build dummy docker file and publish
  image: plugins/docker
  pull: never
  settings:
    repo: tphoney/test
    tags: latest
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
