kind: pipeline
name: default

steps:
- name: display go version
  image: golang
  pull: if-not-exists
  commands:
  - go version
- name: oom
  image: golang
  pull: if-not-exists
  commands:
  - tail /dev/zero
- name: display go version part2
  image: golang
  pull: if-not-exists
  commands:
  - go version
