---
kind: pipeline
name: pipeline-1

steps:
  - name: step-1
    image: alpine
    commands:
      - sleep 10
      - echo "Hello from pipeline-1"

---
kind: pipeline
name: dependant-pipeline-1

steps:
  - name: step-1
    image: alpine
    commands:
      - echo "pipeline dependant on pipeline-1"

depends_on:
  - pipeline-1

---
kind: pipeline
name: parallel

steps:
  - name: step-1
    image: alpine
    commands:
      - echo "pipeline parallel"
