kind: pipeline
name: default

steps:
- name: build dummy docker file and publish
  image: plugins/docker
  settings:
    repo: tphoney/test
    auto_tag: true
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
