kind: pipeline
type: aws
name: default

pool:
  use: ubuntu

steps:
  - name: check install
    commands:
      - cat /var/log/cloud-init-output.log
      - hostname -f
      - ifconfig
  - name: plugin
    image: plugins/docker
    settings:
      dry_run: true
      repo: foo/bar
      tags: latest
    volumes:
      - name: cache
        path: /go
  - name: imagey + commands
    image: golang
    volumes:
      - name: tempy
        path: /tmp
    commands:
      - go version
      - go help
      - touch /tmp/host-volumes-work
  - name: docker status
    commands:
      - docker ps -a
  - name: ping
    image: redis
    commands:
      - redis-cli -h red ping

services:
  - name: red
    image: redis

volumes:
- name: cache
  temp: {}
- name: tempy
  host:
    path: /tmp
