kind: pipeline
type: kubernetes
name: default

steps:
  - name: hello
    image: golang
    commands:
      - uname -a
      - go version
  - name: ping
    image: redis
    commands:
      - sleep 5
      - redis-cli -h red ping
  - name: ping google
    image: plugins/drone-diagnostics
    commands:
      - timeout 40 ping google.com
    depends_on:
      - hello
      
services:
  - name: red
    image: redis
