kind: pipeline
name: default

steps:
- name: display go version
  image: golang
  pull: if-not-exists
  commands:
  - go version
- name: jira
  image: plugins/jira
  pull: never
  settings:
    client_id:
      from_secret: jira_client_id
    client_secret:
      from_secret: jira_client_secret
    instance: droneio
    project: TT
    environment_name: staging
    log_level: debug
    pipeline: bash_plugin
