kind: pipeline
type: vm
name: testing

pool:
  use: testpool

steps:
- name: fix permissions
  commands:
    - sudo chmod -R 777  /tmp/aws
- name: docker
  image: plugins/docker
  settings:
    dockerfile: Dockerfile
    repo: tphoney/test
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    auto_tag: true
    auto_tag_suffix: linux-amd64
- name: manifest
  image: plugins/manifest:1.2
  settings:
    auto_tag: 'true'
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    spec: manifest.yaml
    ignore_missing: true
trigger:
  ref:
  - refs/tags/**
